[package]
name = "archaeodash-analysis"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
archaeodash-domain = { workspace = true }
archaeodash-data-io = { workspace = true }
faer = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }

[lints]
workspace = true
